export const USER_LOGIN_BEGINS = "USER_LOGIN_BEGINS";
export const USER_LOGIN_SUCCESSFUL = "USER_LOGIN_SUCCESSFUL";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_REGISTER_BEGINS = "USER_REGISTER_BEGINS";
export const USER_REGISTER_SUCCESSFUL = "USER_REGISTER_SUCCESSFUL";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const FETCH_PRODUCTS_BEGINS = "FETCH_PRODUCTS_BEGINS";
export const FETCH_PRODUCTS_SUCCESSFUL = "FETCH_PRODUCTS_SUCCESSFUL";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const ADD_PRODUCTS_BEGINS = "ADD_PRODUCTS_BEGINS";
export const ADD_PRODUCTS_SUCCESSFUL = "ADD_PRODUCTS_SUCCESSFUL";
export const ADD_PRODUCTS_FAILURE = "ADD_PRODUCTS_FAILURE";
